fix: Update LANG override
OxSon/dotbot-yay pull request #3
Opened 2021-05-11 18:07 UTC by grzesuav

`LANG=en_US_UTF-8` is locale and does not work. Setting `LANG=en_US` fixes that

2021-05-11 18:08 UTC, grzesuav commented
hi @OxSon , found a small bug, won't mind merging it ?

2021-05-11 23:51 UTC, OxSon commented on yay.py
> +        cmd = 'LANG=en_US yay --needed --noconfirm -S {}'.format(pkg)
Looks good to me. Let's fix the comment on line 70 to match the correction, yes? @grzesuav

2021-05-11 23:52 UTC, OxSon requested changes
Let's make sure the comment on line 70 reflects this fix as well :)

2021-05-11 23:52 UTC, OxSon commented
Thanks for the PR! Would you mind changing the comment as well and then I will accept? Thank you :)

2021-05-12 07:29 UTC, grzesuav commented on yay.py
> +        cmd = 'LANG=en_US yay --needed --noconfirm -S {}'.format(pkg)
done

2021-05-12 16:22 UTC, OxSon commented on yay.py
> +        cmd = 'LANG=en_US yay --needed --noconfirm -S {}'.format(pkg)
Awesome 👍

2021-05-12 16:22 UTC, OxSon commented
Looks great. Thank you for your time.

2021-05-12 16:22 UTC, merged